cfg-version: 11
message: '&cYou have reached the edge of this world.'
round-border: true
debug-mode: false
whoosh-effect: true
portal-redirection: true
knock-back-dist: 3.0
timer-delay-ticks: 5
remount-delay-ticks: 0
dynmap-border-enabled: true
dynmap-border-message: The border of the world.
player-killed-bad-spawn: false
deny-enderpearl: true
fill-autosave-frequency: 30
bypass-list-uuids: []
fill-memory-tolerance: 500
prevent-block-place: false
prevent-mob-spawn: false
worlds:
  world:
    x: 1.0
    z: 1.0
    radiusX: 999999
    radiusZ: 9999999
    wrapping: false
fillTask:
  world: world
  fillDistance: 208
  chunksPerRun: 1
  tickFrequency: 1
  x: -1173
  z: 1174
  length: 2350
  total: 5513292
  forceLoad: false
